version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: step 1
          command: |
            echo "sleep 610" >> ./mock.sh
            chmod +x ./mock.sh
            # use `|| true` to force the overall step as exit 0
            timeout 9m bash ./mock.sh || true
      - run:
          name: step 2
          command: |
            echo "running fine!!!"
