version: 2.1

orbs:
  aws-old: circleci/aws-cli@3.1.3
  aws-new: circleci/aws-cli@4.0.0

jobs:
  build-313:
    docker:
      - image: cimg/base:current
    steps:
      - aws-old/install
      - run: aws --version
  build-400:
    docker:
      - image: cimg/base:current
    steps:
      - aws-new/install
      - run: aws --version
workflows:
  main:
    jobs:
      - build-313
      - build-400
