version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: create
          command: |
            echo "$CIRCLE_SHA1" >> ./sha.txt
      - store_artifacts:
          path: /home/circleci/project/sha.txt
          destination: sha.txt
