version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - run: printenv FOOBAR > foobar.txt
      - store_artifacts:
          path: foobar.txt

workflows:
  main:
    jobs:
      - build:
          context:
            # account context on my Server 4.x
            - dummy
