version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - run: printenv ORG_FOOBAR > foobar.txt
      - store_artifacts:
          path: foobar.txt

workflows:
  main:
    jobs:
      - build:
          context:
            # account context on my Server 4.x
            # switched to using org context, org-dummy, instead of account context.
            # this CI project passes org contexts over for forked PRs.
            - dummy
